# Generated by Django 5.1.1 on 2024-09-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_callrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='encrypted_aes_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='iv',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
